# Generated by Django 4.0.6 on 2023-03-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWords',
        ),
        migrations.DeleteModel(
            name='OriginalAuthors',
        ),
    ]
